[reticulum]
enable_transport = yes
share_instance = no
respond_to_probes = no

[logging]
loglevel = 3

[interfaces]
  [[Noderage backbone]]
    type = TCPClientInterface
    enabled = yes
    target_host = 155.4.245.160
    target_port = 4242
    mode = full
    announce_cap = 1
  [[MichMesh backbone]]
    type = TCPClientInterface
    enabled = yes
    target_host = 173.255.213.18
    target_port = 7822
    mode = full
    announce_cap = 1
